### ISSUE TITLE
Format?

### ISSUE THREAD

**Issue by SinlesFlyer376** [Chris-Prime/FactionsPE#1]
Howwould i format the rank and add like {faction} to it?

**Comment by Chris-Prime** [comment]
I'll implement this function soon, currently this project is going through a rewrite so any suggestion is welcome.

**Comment by SinlesFlyer376** [comment]
So does that mean it is implemented in? Enhanced?

**Comment by PrimusLV** [comment]
No, label is just for organizing the issues!
