### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by ApexDevelops** [Chris-Prime/FactionsPE#11]
thread:CRITICAL  ClassNotFoundException: "Class sll\LibLoader not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by Chris-Prime** [comment]
Here we go again :D

If you cloned this issue using commannd line. Then see this issue #2 if not, then download each sub-module individually.

**Comment by ApexDevelops** [comment]
No matter what I do it doesn't work

**Comment by Chris-Prime** [comment]
Explain more, please.

**Comment by caspervanneck** [comment]
@ApexDevelops clone it with git

**Comment by caspervanneck** [comment]
if you have windows
