### ISSUE TITLE
error at loading.

### ISSUE THREAD

**Issue by Uniqulmuia** [Chris-Prime/FactionsPE#2]
Thats happens when i load the plugin, for other friends is working..

[Tesseract] [11:22:21] [Server thread/INFO]: Loading source plugin FactionsPE v1.0.0_reborn
[Tesseract] [11:22:21] [Server thread/CRITICAL]: ClassNotFoundException: "Class sll\LibLoader not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[Tesseract] [11:22:21] [Server thread/INFO]: Disabling DevTools v1.10.0
Then devtools crashes

**Comment by Chris-Prime** [comment]
If you were downloading the .zip file from Github then it's good to know that it doesn't include submodules. Get them manually or clone this repo with --recursive (-R) option.

**Comment by Uniqulmuia** [comment]
A good method to get the submodules? With an Example

**Comment by Chris-Prime** [comment]
If you're using a git from command line e.g. Linux
```
$ git clone -R https://github.com/Chris-Prime/FactionsPE
```

**Comment by Uniqulmuia** [comment]
root@localhost:~# git clone -R https://github.com/Chris-Prime/FactionsPE
error: unknown switch `R'
usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive           initialize submodules in the clone
    --recurse-submodules  initialize submodules in the clone
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    --dissociate          use --reference only while cloning
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --single-branch       clone only one branch, HEAD or --branch
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository
I m using ubuntu 14 ;-!

**Comment by Chris-Prime** [comment]
Sorry, my fault. I thought that -R is an alias for ```--recursive``` for some reason. Try ```--recursive``` instead.

**Comment by Uniqulmuia** [comment]
I tryed alot and i m not getting the sll files with git..

**Comment by Chris-Prime** [comment]
Thanks for reporting, I've fixed this problem and it should clone the repository correctly by doing
```
$ git clone --recursive https://github.com/Chris-Prime/FactionsPE.git
```
