### ISSUE TITLE
a eror

### ISSUE THREAD

**Issue by caspervanneck** [Chris-Prime/FactionsPE#7]
ClassNotFoundException: "Class sll\LibLoader not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by Chris-Prime** [comment]
How did you install this?

**Comment by caspervanneck** [comment]
devtools @Chris-Prime

**Comment by Chris-Prime** [comment]
I mean how do you get the source code from github? Through a .zip file or cloning via command line?

If you used command line then try looking at issue #2

**Comment by caspervanneck** [comment]
soarce

**Comment by caspervanneck** [comment]
need i  clone it

**Comment by Chris-Prime** [comment]
I'm not getting what you're trying to say? Can you please be more specific?

**Comment by caspervanneck** [comment]
i use github download buton

**Comment by caspervanneck** [comment]
its same eror

**Comment by Chris-Prime** [comment]
Come back when you learn how Github works :+1:
